# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

release:
  github:
    owner: booster-proj
    name: lsaddr
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - make test
builds:
  -
    goos:
      - darwin
      - linux
      - windows
sign:
  artifacts: checksum
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
